# Generated by Django 5.1.15 on 2026-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='keep_signed_in',
            field=models.BooleanField(default=False, help_text='Always keep this user signed in (persistent session), regardless of the login "Remember me" checkbox.'),
        ),
    ]
