# Generated by Django 5.1.15 on 2026-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['group_letter', 'name']},
        ),
        migrations.AddField(
            model_name='team',
            name='group_letter',
            field=models.CharField(blank=True, db_index=True, max_length=1),
        ),
    ]
