# Generated by Django 5.1.15 on 2026-06-05 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('question_text', models.TextField(help_text='Use {home_team} and {away_team} placeholders.')),
                ('question_type', models.CharField(choices=[('choice', 'Choice'), ('numeric', 'Numeric'), ('player_pick', 'Player pick')], default='choice', max_length=20)),
                ('default_points', models.PositiveIntegerField(default=3)),
                ('category', models.CharField(choices=[('winner', 'Winner'), ('goals', 'Goals'), ('player', 'Player'), ('stats', 'Stats'), ('random', 'Random')], default='random', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_booster_limit', models.PositiveIntegerField(default=5)),
                ('ai_predict_hours_before', models.PositiveIntegerField(default=2)),
                ('tournament_active', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'game settings',
                'verbose_name_plural': 'game settings',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('kickoff_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished')], default='scheduled', max_length=20)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('won_in', models.CharField(default='FT', max_length=10)),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.round')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournaments.stadium')),
                ('team_away', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='tournaments.team')),
                ('team_home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['kickoff_at', 'match_number'],
                'unique_together': {('tournament', 'match_number')},
            },
        ),
        migrations.CreateModel(
            name='MatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_booster_used', models.BooleanField(default=False)),
                ('total_points', models.IntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'match')},
            },
        ),
        migrations.CreateModel(
            name='MatchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('points', models.PositiveIntegerField(default=3)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='matches.match')),
                ('question_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.questiontemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=255)),
                ('points_awarded', models.IntegerField(blank=True, null=True)),
                ('match_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='matches.matchprediction')),
                ('match_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='matches.matchquestion')),
            ],
            options={
                'unique_together': {('match_prediction', 'match_question')},
            },
        ),
    ]
